services:
  - type: web
    name: battery-department-portal
    runtime: node
    plan: starter
    region: oregon # You can change this to your preferred region
    buildCommand: ./build.sh
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_APP_URL
        fromService:
          type: web
          name: battery-department-portal
          property: host
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: battery-department-portal
          property: host
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: battery-department-db
          property: connectionString
      # Stripe Configuration
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      # Email Configuration
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM
        value: noreply@batterydepartment.com
      # Analytics (Optional)
      - key: NEXT_PUBLIC_GA_ID
        sync: false
      - key: NEXT_PUBLIC_META_PIXEL_ID
        sync: false
      # Feature Flags
      - key: NEXT_PUBLIC_ENABLE_CHAT
        value: "true"
      - key: NEXT_PUBLIC_ENABLE_QUIZ
        value: "true"
      - key: NEXT_PUBLIC_ENABLE_FLEET_MANAGEMENT
        value: "true"
      # API Keys (Optional)
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: battery-department-db
    plan: starter
    databaseName: battery_department
    user: battery_user
